### PR TITLE
Limit Job Parallelism

### PR DESCRIPTION
**Pull request by sgpthomas**
The main changes are:
 - use a custom runtime so that we can limit the thread pool size
 - replace use of tokio::process::Command with std::process::Command so that the number of tokio threads corresponds with the number of spawned Commands.

The one big decision I made was to prioritize breadth first parallelism rather then depth first. Given the following suites:
```
suiteA: [a1, a2, a3, a4]
suiteB: [b1, b2, b3, b4, b5]
suiteC: [c1, c2, c3, c4]
```
Given more parallelism, `runt` will schedule `[a1, b1, c1]` over `[a1, a2, a3]`. The reason for this is that I start all the "suite schedulers" at the beginning and let them compete over the thread pool. This was just easier to implement than the alternative which would be having a unified scheduler over all tasks and then allocating threads based pm the order of the tasks.

Let me know if you want to keep the new tests. I was using them to debug the order in which tasks were being started.

### CODE REVIEW

**Comment by rachitnigam** [comment]
Code looks good. What were you using the tests to debug? That it is executing the tests in parallel?

**Comment by sgpthomas** [comment]
executing the tests in parallel and making sure that the right number of tests were running at a time by using print statements. couldn't think of a way to test this automatically without leaving the print statements in making sure they were deterministic in some way.

**Comment by sgpthomas** [comment]
should we bump the runt version?

**Comment by rachitnigam** [comment]
I can do `cargo publish` post merge. Can you add a description in the CHANGELOG for what changed (new CLI flag etc.) Leaving the tests in seems fine.

**Comment by sgpthomas** [comment]
done. I'll let you merge when you're ready

**Pull request merged**
